import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GlobalScrollEffects } from "@/components/common/GlobalScrollEffects";
import { CustomCursor } from "@/components/common/CustomCursor";
import { FloatingContact } from "@/components/common/FloatingContact";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quickgen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CustomCursor />
        <GlobalScrollEffects>{children}</GlobalScrollEffects>
        <FloatingContact />
      </body>
    </html>
  );
}
